#
# Main GitHub Actions Workflow file.
# CI build.
#

name: Lazuli CI Build

on: [push]

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: [AVR_ATmega328p]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build docker image # TODO: Maybe build docker image out of the matrix.
        run: docker image build -t lazuli .
        
      - name: Run Lazuli container
        run: docker run -tid --rm --name lazuli_container -v$(pwd):/~/workspace:z lazuli
        
      - name: CMake Configure (for target machine ${{matrix.machine}})
        run: docker exec lazuli_container bash -c "cmake -S . -B ./build -DLZ_TARGET_MACHINE_CHOICE=${{matrix.machine}}"
        
      - name: CMake Build
        run: docker exec lazuli_container bash -c "./.compile.sh"

  checks:
    name: Checks job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Check line length, trailing whitespaces and tabs
        run: ./.checklines.sh

  doxygen: # TODO: Run this job inside a container.
    name: Doxygen job - Build Doxygen documentation from code comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

        # Ugly hack to force the parameter QUIET to NO only in this
        # CI situation (for logs).
      - name: Run Doxygen
        run: cat Doxyfile | sed  "/^QUIET.*=/c\QUIET = NO" | doxygen -

  sphinx: # TODO: Run this job inside a container.
    name: Sphinx job - Build Sphinx documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sphinx
        run: sudo apt-get install -y make python3-sphinx

      - name: Run Sphinx
        run: cd doc && make
