#
# Main GitHub Actions Workflow file.
# CI build.
#

name: Lazuli CI Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine: [AVR_ATmega328p]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # This is to install the ts command
      - name: Install complementary tools
        run: sudo apt-get install -y moreutils

        # We set the bash option "pipefail" to get the exit code of a failed
        # command in a pipeline.
        # We pipe the Docker build output to ts in order to have timestamps on
        # each build step.
        # The first time stamp is a stopwatch since the invocation of
        # "docker build".
        # The second timestamp is the time taken since the previous print.
      - name: Build docker image # TODO: Maybe build docker image out of the matrix.
        run: set -o pipefail && docker version && { docker image build -t lazuli . | ts -i "%H:%M:%S  " | ts -s "%H:%M:%S  " ; }

      - name: Run Lazuli container
        run: docker run -id --rm --name lazuli -v$(pwd):/~/workspace:z lazuli

      - name: CMake Configure (for target machine ${{matrix.machine}})
        run: docker exec lazuli bash -c "cmake -S . -B ./build -DLZ_TARGET_MACHINE_CHOICE=${{matrix.machine}}"

      - name: CMake Build
        run: docker exec lazuli bash -c "time ./.compile.sh"

  checks:
    name: Checks job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check line length, trailing whitespaces and tabs
        run: ./scripts/checklines.sh

  doxygen: # TODO: Run this job inside a container.
    name: Doxygen job - Build Doxygen documentation from code comments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Doxygen version
        run: doxygen --version

        # Ugly hack to force the parameter QUIET to NO only in this
        # CI situation (for logs).
      - name: Run Doxygen
        run: cat Doxyfile | sed  "/^QUIET.*=/c\QUIET = NO" | doxygen -

  sphinx: # TODO: Run this job inside a container.
    name: Sphinx job - Build Sphinx documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Sphinx
        run: sudo apt-get install -y make python3-sphinx

      - name: Run Sphinx
        run: cd doc && make
